### ISSUE TITLE
AwesomeOpenSource

### ISSUE THREAD

**Issue by jeffreyjackson** [Kikobeats/awesome-github#1]
We are creating a github org for all awesome open source repos. I am working with a few individuals who are also managing their own awesome repos, and I think to gain more traction we need to work together. What are your thoughts about collectively moving your awesome repos to https://github.com/AwesomeOpenSource

The idea is that visibility for these repos would be increased due to more traffic to the org. What are your thoughts? Let me know if there is anything you'd like to discuss!

**Comment by ghost** [comment]
Great idea :+1: 

Much better than the current state of things with `awesome <this> and <that>` all over the place.

You do need a cool logo and maybe a simpler title? `awesomelists` is availaible last I checked.

**Comment by jeffreyjackson** [comment]
I already made a bunch of invites to /AwesomeOpenSource.  Maybe we can make the switch in a couple weeks?  

I'll get some designers on the logo too!  any ideas on how we can get some designers to contribute and we vote for the best?

I'll invite you in and make you an admin.  Looking forward to this!

**Comment by jeffreyjackson** [comment]
cc @dkhamsing

**Comment by ghost** [comment]
@jeffreyjackson I can help you finding more awesome repos! Are you keeping a list somewhere?

**Comment by jeffreyjackson** [comment]
not yet, we can start one in /AwesomeOpenSource if you want.  Also, https://github.com/bayandin/awesome-awesomeness is pretty good too, but I think we should have all of this under an org to ensure it will always be supported.

**Comment by ghost** [comment]
Sounds good to me!

**Comment by dkhamsing** [comment]
A list would be great as a central place for repos that have yet to move.. or that won't move

**Comment by jeffreyjackson** [comment]
I like that, whats a good name for it?

**Comment by jeffreyjackson** [comment]
how about "invites"

**Comment by ghost** [comment]
@dkhamsing Yes, that's what I tried to say. Well, this could be handled via an issue with a list of checkboxes.

**Comment by jeffreyjackson** [comment]
each repo should be all inclusive for that particular topic.  (e.g. mac-apps is a list of all awesome open source mac apps)

**Comment by jeffreyjackson** [comment]
@bucaran you're in charge.  I'm making a repo and cutting you loose bro!

**Comment by Kikobeats** [comment]
I fell that awesome-awesomeness is the key, so is enough for expose other repositories

**Comment by jeffreyjackson** [comment]
The problem is that its not very active.  It hasnt been updated in months.  Some of the PRs there are from January :cry:

**Comment by dkhamsing** [comment]
Yeah it would be great if there was an active collaborator

**Comment by Kikobeats** [comment]
@jeffreyjackson I think that you need less effort if you try to contact with the creator that creating a organization and add all popular repositories...

**Comment by ghost** [comment]
Sharing a large organization with all the awesome maintainers would be more exciting than _awesome-awesomeness_.

**Comment by Kikobeats** [comment]
@bucaran true!

**Comment by inputsh** [comment]
You guys do realize that there's a repository called just awesome? It's a list with a _huge_ number of other lists hosted on GitHub. It is regularly updated and maintained and has a large support (~900 people watching, ~11k stars, ~1.1k forks). It made awesome-awesomeness obsolete in every single way.

https://github.com/sindresorhus/awesome

**Comment by ghost** [comment]
@aleksandar-todorovic IMO this shouldn't be a repo maintained by a user, but an _organization_'s repository. You are welcome to disagree of course :smile:

**Comment by Kikobeats** [comment]
finally?
